#!/usr/bin/env python3
"""Enable/disable SWRSToys modules by editing ModLoaderSettings.json.

    ops/soku_mods.py list
    ops/soku_mods.py set sokuframeextractor/sokuframeextractor=off
    ops/soku_mods.py ablation     # the set the local arena wants
    ops/soku_mods.py netplay      # the set the online match wants

WHY A SCRIPT AND NOT AN EDITOR
------------------------------
`SWRSToys.ini` says "DO NOT MODIFY / autogenerated by SokuModLoader"; the real
store is `ModLoaderSettings.json`. Editing the wrong one of those two looks
like it worked and changes nothing.

WHY MODULES ARE NAMED `dir/dll` AND NOT BY DLL STEM
---------------------------------------------------
This file carries 54 keys and they are NOT unique by DLL name. Measured:

  Modules\\SokuFrameExtractor\\SokuFrameExtractor.dll      enabled
  Modules\\SokuFrameExtractor.bak\\SokuFrameExtractor.dll  disabled
  Modules\\giuroll\\giuroll.dll         disabled   <- capital M, the live set
  modules\\giuroll\\giuroll.dll         disabled   <- lowercase duplicate

so "SokuFrameExtractor" names two different DLLs and "giuroll" names two
different spellings of one. A stem match would silently flip the `.bak` copy
too. Keys are therefore matched on `directory/dll`, lowercased, and the write is
DELIBERATELY ASYMMETRIC:

  disabling  -> every key that matches, both spellings, so no stray copy is
                left enabled;
  enabling   -> exactly ONE key, the canonical `Modules\\` spelling.

Enabling both spellings would hand the loader the same DLL twice. The first
version of this script did that to WindowResizer and it is the reason the rule
is written down rather than inferred.

Every full key written is printed.
"""
from __future__ import annotations

import json
import shutil
import sys
from pathlib import Path

GAME = Path.home() / ".wine-soku/drive_c/Games/Soku"
SETTINGS = GAME / "ModLoaderSettings.json"

# Only modules whose state we deliberately manage; anything else keeps whatever
# is already set.
#
# giuroll is OFF for local ablation runs on purpose: it replaces the frame
# limiter ([FramerateFix] spin_amount=1500 in giuroll.ini), so leaving it on
# would make every arm's timing differ from the numbers already on record. It
# goes on for netplay, where it is the entire point, and the latency gate is
# re-measured with it enabled before any online match.
#
# SokuFrameExtractor is OFF in both: its deployed .ini still points at a
# finished collection job (`ReplayDir = Z:\out\.work\replay`), so Initialize()
# returns false and SWRSToys raises the modal "module failed" dialog on every
# launch. Nothing in live play needs the extractor.
PRESETS = {
    "ablation": {
        "sokuframeextractor/sokuframeextractor": False,
        "sokuframeextractor.bak/sokuframeextractor": False,
        "giuroll/giuroll": False,
        "giuroll-ui/giuroll_ui": False,
        "windowresizer/windowresizer": True,
    },
    "netplay": {
        "sokuframeextractor/sokuframeextractor": False,
        "sokuframeextractor.bak/sokuframeextractor": False,
        "giuroll/giuroll": True,
        "giuroll-ui/giuroll_ui": True,
        "windowresizer/windowresizer": True,
    },
}


def load() -> dict:
    if not SETTINGS.is_file():
        sys.exit(f"no settings at {SETTINGS}")
    return json.loads(SETTINGS.read_text())


def ident(key: str) -> str:
    """`Modules\\giuroll\\giuroll.dll` -> `giuroll/giuroll`."""
    parts = key.replace("\\", "/").split("/")
    return f"{parts[-2]}/{parts[-1].removesuffix('.dll')}".lower()


def show(d: dict) -> None:
    seen: dict[str, list[str]] = {}
    for key, v in d["modules"].items():
        seen.setdefault(ident(key), []).append(
            f"{'ON ' if v.get('enabled') else 'off'} {key}")
    for name in sorted(seen):
        for line in sorted(seen[name]):
            print(f"  {line}")


def canonical(keys: list[str]) -> str:
    """The one key to switch ON when a module is spelled more than once.

    Prefer the capitalised `Modules\\` directory -- that is the spelling
    SWRSToys.ini was generated from and therefore the one the loader is
    already using. Ties break on the shortest key so a `.bak` or `-old`
    sibling never wins.
    """
    ranked = sorted(keys, key=lambda k: (not k.startswith("Modules\\"), len(k), k))
    return ranked[0]


def apply(d: dict, wanted: dict[str, bool]) -> list[str]:
    by_name: dict[str, list[str]] = {}
    for key in d["modules"]:
        by_name.setdefault(ident(key), []).append(key)

    moved = []
    for name, on in wanted.items():
        keys = by_name.get(name)
        if not keys:
            continue
        # OFF everywhere; ON in exactly one place.
        targets = {k: (on if k == canonical(keys) else False) for k in keys} \
            if on else {k: False for k in keys}
        for key, val in targets.items():
            v = d["modules"][key]
            if bool(v.get("enabled")) != val:
                v["enabled"] = val
                moved.append(f"{'on ' if val else 'off'}  {key}")
    missing = sorted(set(wanted) - set(by_name))
    if missing:
        sys.exit(f"not present in {SETTINGS.name}: {missing}\n"
                 "Modules are named `directory/dll`, lowercased. Run `list`.")
    return moved


def main(argv: list[str]) -> int:
    if len(argv) < 2 or argv[1] == "list":
        show(load())
        return 0
    if argv[1] in PRESETS:
        wanted = dict(PRESETS[argv[1]])
    elif argv[1] == "set":
        wanted = {}
        for arg in argv[2:]:
            name, _, val = arg.partition("=")
            if val not in ("on", "off"):
                sys.exit(f"expected NAME=on|off, got {arg!r}")
            wanted[name.lower()] = val == "on"
        if not wanted:
            sys.exit("`set` needs at least one NAME=on|off")
    else:
        sys.exit(__doc__)

    d = load()
    backup = SETTINGS.with_suffix(".json.presfe")
    if not backup.exists():
        shutil.copy2(SETTINGS, backup)
        print(f"first-run backup -> {backup.name}")
    moved = apply(d, wanted)
    SETTINGS.write_text(json.dumps(d, indent=4) + "\n")
    print("changed:")
    for line in moved or ["  nothing"]:
        print(f"  {line}" if moved else line)
    # Re-read rather than trusting the write: that is the whole point.
    print("loader will see:")
    show(load())
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
